-- Create table for global app settings directly in public schema
create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.app_settings enable row level security;

-- Policies for app_settings
create policy "Enable read access for all users" on public.app_settings
  for select using (true);

create policy "Enable insert for authenticated users only" on public.app_settings
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.app_settings
  for update using (auth.role() = 'authenticated');

-- Insert default settings if not exists
insert into public.app_settings (key, value)
values ('general', '{
  "churchName": "IASD Vila Pinheiro",
  "welcomeText": "Este portal apresenta a destinação fiel dos recursos sagrados entregues à igreja.",
  "bibleVerse": {
    "text": "Ora, o que se requer dos despenseiros é que cada um deles seja encontrado fiel.",
    "reference": "1 Coríntios 4:2"
  },
  "visibleMonths": []
}'::jsonb)
on conflict (key) do nothing;
