-- Rode este comando no editor SQL do Supabase para criar a tabela

create table transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null check (type in ('income', 'expense')),
  date date not null,
  description text not null,
  value numeric not null,
  category text not null,
  user_id uuid default auth.uid()
);

-- Habilitar segurança (RLS)
alter table transactions enable row level security;

-- Política: Todos podem VER (Público)
create policy "Todos podem ver transações"
on transactions for select
to anon
using (true);

-- Política: Apenas autenticados podem INSERIR/EDITAR/DELETAR
create policy "Admins podem fazer tudo"
on transactions for all
to authenticated
using (true);
